In [2]:
import numpy as np

In [ ]:
a = np.random.randn(3, 4) # Matrice de 3 par 4
print(a)

[[-0.38153679 -0.02875454 -1.4949321   1.44674867]
 [-0.3674659  -0.6970477  -1.16935636 -0.86384615]
 [-0.58955648  0.78864445  0.42396542  0.13098191]]


In [ ]:
b = np.random.randn(4) # Matrice de 4 par 1
print(b)

[-2.071012   -0.05078264 -0.53175908  0.96689732]


In [5]:
c = a + b        # broadcasting colonne
print(c)

[[-2.45254878 -0.07953718 -2.02669118  2.41364599]
 [-2.43847789 -0.74783034 -1.70111544  0.10305117]
 [-2.66056847  0.73786182 -0.10779367  1.09787923]]


In [ ]:
d = a @ b        # produit matriciel
print(d)

# Pour faire un produit matriciel, le nombre de colonne de A doit 
# être équivalent au nombre de ligne de B. Il s'agit ensuite d'un produite
# scalaire

[2.98542863 0.58298954 1.08212769]


In [9]:
e = np.linalg.svd(a)  # valeurs singulières
print(e)

SVDResult(U=array([[ 0.91662018,  0.39939783, -0.01699484],
       [ 0.36754731, -0.82527942,  0.42874567],
       [-0.1572146 ,  0.39924334,  0.90326537]]), S=array([2.18629706, 1.69455384, 0.85080215]), Vh=array([[-0.17934367, -0.18594976, -0.85383285,  0.45191591],
       [-0.04986529,  0.51850561,  0.3170383 ,  0.79256047],
       [-0.80346671,  0.48658518, -0.10930517, -0.32515919],
       [-0.56550027, -0.67809254,  0.39813133,  0.24877984]]))
